# Generated by Django 4.1.10 on 2026-02-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0003_delete_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="features",
            field=models.ManyToManyField(blank=True, to="roles.feature"),
        ),
    ]
